# Generated by Django 2.1.2 on 2018-11-03 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Groups', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=150)),
                ('complete', models.BooleanField(default=False)),
                ('assigned_to', models.CharField(max_length=40)),
            ],
        ),
    ]
